# Generated by Django 5.2.12 on 2026-05-01 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockorder',
            name='restock_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
