# Generated by Django 5.2.12 on 2026-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_restockorder_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockorder',
            name='restock_date',
            field=models.DateField(),
        ),
    ]
