# Generated by Django 5.2.12 on 2026-05-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=150)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('StockQuantity', models.IntegerField(default=0)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('Height', models.IntegerField(blank=True, null=True)),
                ('Width', models.IntegerField(blank=True, null=True)),
                ('Length', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False)),
                ('Image_URL', models.CharField(max_length=500)),
                ('Is_Primary', models.SmallIntegerField(default=0)),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'db_table': 'ProductImage',
            },
        ),
    ]
