# Generated by Django 5.2.13 on 2026-04-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.warehouselocation'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='ProductID',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
    ]
