# Generated by Django 5.2.12 on 2026-05-01 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_category_product_location_product_supplier'),
        ('stock', '0003_alter_restockorder_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryID',
            field=models.AutoField(db_column='category_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(db_column='category_name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=models.CharField(blank=True, db_column='color', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Height',
            field=models.IntegerField(blank=True, db_column='height', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Length',
            field=models.IntegerField(blank=True, db_column='length', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.AutoField(db_column='product_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(db_column='product_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='StockQuantity',
            field=models.IntegerField(db_column='stock_quantity', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Width',
            field=models.IntegerField(blank=True, db_column='width', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, db_column='image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.supplier'),
        ),
    ]
