# Generated by Django 5.2.12 on 2026-04-25 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(db_column='CustomerID', unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate')),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='LastUpdated')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(db_column='DeliveryID', primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_column='OrderID', unique=True)),
                ('address_id', models.IntegerField(db_column='AddressID')),
                ('status', models.CharField(choices=[('PENDING', 'รอการจัดส่ง'), ('SHIPPED', 'จัดส่งแล้ว'), ('IN_TRANSIT', 'อยู่ระหว่างจัดส่ง'), ('DELIVERED', 'ส่งสำเร็จ'), ('FAILED', 'จัดส่งไม่สำเร็จ'), ('CANCELLED', 'ยกเลิก')], db_column='Status', default='PENDING', max_length=20)),
                ('courier_name', models.CharField(blank=True, choices=[('KERRY', 'Kerry Express'), ('FLASH', 'Flash Express'), ('THAILAND_POST', 'Thailand Post'), ('J_AND_T', 'J&T Express'), ('SHOPEE', 'Shopee Express'), ('OTHER', 'อื่นๆ')], db_column='CourierName', default='', max_length=30)),
                ('tracking_number', models.CharField(blank=True, db_column='TrackingNumber', default='', max_length=64)),
                ('delivery_date', models.DateTimeField(blank=True, db_column='DeliveryDate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'Delivery',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(db_column='CartItemID', primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(db_column='ProductID')),
                ('quantity', models.PositiveIntegerField(db_column='Quantity', default=1)),
                ('cart_item_total', models.DecimalField(db_column='CartItem_Total', decimal_places=2, default=0, max_digits=12)),
                ('added_date', models.DateTimeField(auto_now_add=True, db_column='AddedDate')),
                ('cart', models.ForeignKey(db_column='CartID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_delivery.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'Cart_Item',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product_id'), name='uq_cart_product'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_cartitem_qty_positive')],
            },
        ),
    ]
