# Generated by Django 5.2.12 on 2026-04-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uq_cart_product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item_total',
            new_name='cartitem_total',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='courier_name',
            new_name='delivery_name',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='uq_cart_product'),
        ),
    ]
