# Generated by Django 5.2.12 on 2026-04-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_delivery', '0002_remove_cartitem_uq_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_id',
            field=models.AutoField(db_column='Item_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.IntegerField(db_column='AddressID', help_text='FK -> Customer_Address.AddressID'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, db_column='DeliveryDate', help_text='วันที่จัดส่งสินค้า', null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_name',
            field=models.CharField(blank=True, db_column='DeliveryName', default='', help_text='ชื่อบริษัทขนส่ง เช่น Kerry, Flash, SCG', max_length=150),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.IntegerField(db_column='OrderID', help_text='FK -> Sale_Order.OrderID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, db_column='TrackingNumber', default='', help_text='เลขติดตามพัสดุ (ได้จากขนส่งหลัง pickup)', max_length=13),
        ),
    ]
