# Generated by Django 5.2.12 on 2026-05-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_delivery', '0003_remove_delivery_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cartitem_total',
            field=models.DecimalField(db_column='CartItem_Total', decimal_places=2, default=0, help_text='ราคารวมของรายการนี้ (Price * Quantity)', max_digits=12),
        ),
    ]
