# Generated by Django 5.2.12 on 2026-04-17 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNumber', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('AddressID', models.AutoField(primary_key=True, serialize=False)),
                ('AddressType', models.CharField(max_length=50)),
                ('HouseNo', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=50)),
                ('SubDistrict', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('ZipCode', models.CharField(max_length=5)),
                ('is_default', models.BooleanField(default=False)),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'db_table': 'Customer_Address',
            },
        ),
    ]
