# Generated by Django 5.2.12 on 2026-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
