# Generated by Django 5.2.12 on 2026-04-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], max_length=50),
        ),
    ]
