# Generated by Django 5.2.12 on 2026-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('intransit', 'In Transit'), ('received', 'Received'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
