# Generated by Django 5.2.12 on 2026-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('intransit', 'In Transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
