# Generated by Django 5.2.12 on 2026-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EFirstName', models.CharField(max_length=100)),
                ('ELastName', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=10)),
                ('EPhone', models.CharField(max_length=20)),
                ('EEmail', models.CharField(max_length=100, unique=True)),
                ('EPassword', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
