# Generated by Django 5.2.12 on 2026-05-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
