# Generated by Django 5.2.12 on 2026-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='track_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
