# Generated by Django 5.2.12 on 2026-05-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_payment', '0002_saleorder_track_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('In transit', 'In transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
